// داخل كائن ar
"category.text": "نصوص",
"category.image": "صور",
"category.video": "فيديو",
"category.audio": "صوت",
"category.programming": "برمجة",
"category.analysis": "تحليل",
"category.productivity": "إنتاجية",
"category.marketing": "تسويق",
"category.design": "تصميم",
"category.games": "ألعاب",

// داخل كائن en
"category.text": "Text",
"category.image": "Image",
"category.video": "Video",
"category.audio": "Audio",
"category.programming": "Programming",
"category.analysis": "Analysis",
"category.productivity": "Productivity",
"category.marketing": "Marketing",
"category.design": "Design",
"category.games": "Games",
